[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "cells"
version = "0.0"
description = "Unsupervised int64-valued transformers form a self-predicting autoencoder"
requires-python = ">=3.13"
dependencies = [
]

[project.optional-dependencies]
test = [
]

[project.scripts]
runcells = "src.run:main"

[tool.setuptools.packages.find]
where = ["."]
include = ["src*"]